[book]
authors = ["Alexis Williams"]
language = "en"
src = "src"
title = "terranix-codegen"

[output.html]
default-theme = "latte"
preferred-dark-theme = "frappe"
additional-css = ["./theme/catppuccin.css"]
git-repository-url = "https://github.com/synapdeck/terranix-codegen"
edit-url-template = "https://github.com/synapdeck/terranix-codegen/edit/master/{path}"
